name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许你在 GitHub 页面手动点击按钮测试运行

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          # 这里的 URL 是你的项目地址
          curl -I -X GET 'https://ejnvwrxkyijsuyochcqo.supabase.co/rest/v1/holyfamily?select=*&limit=1' \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
